apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim-kmanager
  labels:
    name: mysql-claim-kmanager
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
